service: html2pdf
provider:
  name: aws
  profile: daymaker
  runtime: nodejs12.x
  apiGateway:
    binaryMediaTypes:
      - '*/*'

plugins:
  - serverless-offline

functions:
  pdf:
    handler: handler.downloadPdf
    memorySize: 1536MB
    timeout: 30
    events:
      - http:
          path: /
          method: get
